# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "bingo's log"
baseURL = 'https://binlog.xyz/'
defaultContentLanguage = "zh-cn"
languageCode = 'zh-CN'
hasCJKLanguage = true
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
theme = 'FixIt'

# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
    [menu.main.params]
      icon = "fa-solid fa-archive"
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-th"
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"

# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

[params]
  version = "0.2.X"
  description = "bingo的个人博客"
  keywords = ["bingo", "blog"]
  defaultTheme = "auto"
  gitRepo = ""
  fingerprint = ""
  dateFormat = "2006-01-02"
  images = ["/logo.png"]
  enablePWA = true
  externalIcon = true
  disableThemeInject = false

  [params.author]
    name = "bingo"
    email = "bingo084@outlook.com"
    link = "https://binlog.xyz/"
    avatar = ""

  [params.app]
    title = "bingo's log"
    noFavicon = false
    svgFavicon = ""
    iconColor = "#5bbad5"
    tileColor = "#da532c"
    [params.app.themeColor]
      light = "#f8f8f8"
      dark = "#252627"

  [params.search]
    enable = true
    type = "fuse"
    contentLength = 4000
    [params.search.fuse]
      minMatchCharLength = 2

  [params.header]
    [params.header.title]
      logo = "/logo.png"
      name = "bingo's log"
      typeit = false
    [params.header.subtitle]
      name = "记录生活，分享知识"
      typeit = true

  [params.footer]
    enable = true
    hugo = true
    copyright = true
    author = true
    since = "2021"
    wordCount = true
    icp = '<a rel="license external nofollow noopener noreferrer" href="https://beian.miit.gov.cn/" target="_blank">闽ICP备2021018106号-3</a>'
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
    [params.footer.siteTime]
      enable = true
      animate = true
      icon = "fa-solid fa-heartbeat"
      value = "2021-11-04T09:09:36+08:00"
    [params.footer.order]
      powered = 0
      copyright = 0
      statistics = 0
      visitor = 0
      beian = 0

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10
    [params.section.recentlyUpdated]
      enable = true
      rss = false
      days = 30
      maxCount = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.tagcloud]
    enable = true
    min = 14
    max = 32
    peakCount = 10
    orderby = "name"

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = "bingo084@outlook.com"
      avatarMenu = "/categories/"
      title = "Hi, I'm bingo."
      subTitle = "Keep learning, keep thinking."
      typeit = true
      social = true

  # FixIt 0.2.16 | CHANGED Social config about the author
  [params.social]
    GitHub = "bingo084"
    Telegram = "bingo084"
    Steam = "bingo084"
    Bilibili = "37556054"
    QQ = "954701435"
    Email = "bingo084@outlook.com"
    RSS = true

  [params.page]
    authorAvatar = true
    hiddenFromHomePage = false
    hiddenFromSearch = false
    hiddenFromRss = false
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
    linkToMarkdown = true
    rssFullText = false
    pageStyle = "narrow"
    autoBookmark = false
    wordCount = true
    readingTime = true
    endFlag = ""
    instantPage = false

    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
      position = "right"
    [params.page.expirationReminder]
      enable = true
      reminder = 90
      warning = 180
      closeComment = false
    [params.page.math]
      enable = true
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      copyTex = true
      mhchem = true
    [params.page.code]
      copy = true
      edit = true
      maxShownLines = 10
    [params.page.edit]
      enable = true
      url = ""
    [params.page.share]
      enable = false
    [params.page.comment]
      enable = false
      [params.page.comment.artalk]
        enable = false
        server = "https://yourdomain"
        site = "默认站点"
        placeholder = ""
        noComment = ""
        sendBtn = ""
        editorTravel = true
        flatMode = "auto"
        # FixIt 0.2.17 | CHANGED enable lightgallery support
        lightgallery = false
        locale = "" # FixIt 0.2.15 | NEW
        # FixIt 0.2.18 | NEW
        emoticons = ""
        nestMax = 2
        nestSort = "DATE_ASC" # ["DATE_ASC", "DATE_DESC", "VOTE_UP_DESC"]
        vote = true
        voteDown = false
        uaBadge = true
        listSort = true
        imgUpload = true
        preview = true
        versionCheck = true
      # FixIt 0.1.1 | NEW Disqus comment config (https://disqus.com)
      [params.page.comment.disqus]
        enable = false
        # Disqus shortname to use Disqus in posts
        shortname = ""
      # FixIt 0.1.1 | NEW Gitalk comment config (https://github.com/gitalk/gitalk)
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Valine comment config (https://github.com/xCss/Valine)
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta = ""
        requiredFields = ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        # FixIt 0.2.6 | NEW emoji data file name, default is "google.yml"
        # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
        # located in "themes/FixIt/assets/lib/valine/emoji/" directory
        # you can store your own data files in the same path under your project:
        # "assets/lib/valine/emoji/"
        emoji = ""
        commentCount = true # FixIt 0.2.13 | NEW
      # FixIt 0.2.16 | CHANGED Waline comment config (https://waline.js.org)
      [params.page.comment.waline]
        enable = false
        serverURL = ""
        pageview = false # FixIt 0.2.15 | NEW
        emoji = ["//unpkg.com/@waline/emojis@1.1.0/weibo"]
        meta = ["nick", "mail", "link"]
        requiredMeta = []
        login = "enable"
        wordLimit = 0
        pageSize = 10
        imageUploader = false # FixIt 0.2.15 | NEW
        highlighter = false # FixIt 0.2.15 | NEW
        comment = false # FixIt 0.2.15 | NEW
        texRenderer = false # FixIt 0.2.16 | NEW
        search = false # FixIt 0.2.16 | NEW
        recaptchaV3Key = "" # FixIt 0.2.16 | NEW
        reaction = false # FixIt 0.2.18 | NEW
      # Facebook comment config (https://developers.facebook.com/docs/plugins/comments)
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      # FixIt 0.2.0 | NEW Telegram comments config (https://comments.app)
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      # FixIt 0.2.0 | NEW Commento comment config (https://commento.io)
      [params.page.comment.commento]
        enable = false
      # FixIt 0.2.5 | NEW Utterances comment config (https://utteranc.es)
      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
      # FixIt 0.2.13 | NEW Twikoo comment config (https://twikoo.js.org/)
      [params.page.comment.twikoo]
        enable = false
        envId = ""
        region = ""
        path = ""
        visitor = true
        commentCount = true
        # FixIt 0.2.17 | CHANGED enable lightgallery support
        lightgallery = false
        # FixIt 0.2.17 | NEW enable Katex support
        katex = false
      # FixIt 0.2.14 | NEW Giscus comments config
      [params.page.comment.giscus]
        enable = false
        repo = ""
        repoId = ""
        category = ""
        categoryId = ""
        mapping = ""
        strict = "0" # FixIt NEW | 0.2.18
        term = ""
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom" # ["top", "bottom"]
        lightTheme = "light"
        darkTheme = "dark"
        lazyLoad = true
    [params.page.seo]
      images = []
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""

  [params.pangu]
    enable = true
    selector = "article"

  [params.ibruce]
    enable = true
    enablePost = true

  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
    so = ""
    sogou = ""

  [params.seo]
    image = ""
    thumbnailUrl = ""

  [params.analytics]
    enable = false
    [params.analytics.google]
      id = ""
      anonymizeIP = true
    [params.analytics.fathom]
      id = ""
      server = ""

  [params.cookieconsent]
    enable = false
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  [params.cdn]
    data = ""

  [params.gravatar]
    enable = true
    host = "www.gravatar.com"
    style = ""

  [params.readingProgress]
    enable = true
    light = "orange"
    dark = "orange"
  
  [params.pace]
    enable = true
    color = "orange"

  [params.customFilePath]
    profile = "custom/profile.html"
  
# -------------------------------------------------------------------------------------
# Modules Configuration
# See: https://gohugo.io/hugo-modules/configuration/#module-config-imports
# -------------------------------------------------------------------------------------

[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"

# -------------------------------------------------------------------------------------
# Markup related configuration in Hugo
# See: https://gohugo.io/getting-started/configuration-markup/
# -------------------------------------------------------------------------------------

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# -------------------------------------------------------------------------------------
# Sitemap Configuration
# See: https://gohugo.io/templates/sitemap-template/#configuration
# -------------------------------------------------------------------------------------

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

[Permalinks]
  posts = "posts/:slugorfilename"

# -------------------------------------------------------------------------------------
# Privacy Configuration
# See: https://gohugo.io/about/hugo-and-gdpr/
# -------------------------------------------------------------------------------------

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# -------------------------------------------------------------------------------------
# Media Types
# See: https://gohugo.io/templates/output-formats/#media-types
# -------------------------------------------------------------------------------------

[mediaTypes]
  [mediaTypes."text/markdown"]
    suffixes = ["md"]
  [mediaTypes."text/plain"]
    suffixes = ["txt"]

# -------------------------------------------------------------------------------------
# Output Format Definitions
# See: https://gohugo.io/templates/output-formats/#output-format-definitions
# -------------------------------------------------------------------------------------

[outputFormats]
  [outputFormats.MarkDown]
    mediaType = "text/markdown"
    isPlainText = true
    isHTML = false
  [outputFormats.BaiduUrls]
    baseName = "baidu_urls"
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false

# -------------------------------------------------------------------------------------
# Customizing Output Formats
# See: https://gohugo.io/templates/output-formats/#customizing-output-formats
# -------------------------------------------------------------------------------------

[outputs]
  home = ["HTML", "RSS", "JSON", "BaiduUrls"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML", "RSS"]
