# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "bingo's log"
baseURL = 'https://www.binlog.cc/'
defaultContentLanguage = "zh-cn"
languageCode = 'zh-CN'
hasCJKLanguage = true
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
theme = 'FixIt'

# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
    [menu.main.params]
      icon = "fa-solid fa-archive"
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-th"
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"

# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

[params]
  description = "bingo的个人博客"
  keywords = ["bingo", "blog"]
  enablePWA = true
  externalIcon = true
  indexWithSubtitle = true

  [params.author]
    name = "bingo"
    email = "bingo084@outlook.com"
    link = "https://github.com/bingo084"

  [params.gitInfo]
    repo = "https://github.com/bingo084/blog"

  [params.app]
    title = "bingo's log"
    iconColor = "#5bbad5"
    tileColor = "#da532c"
    [params.app.themeColor]
      light = "#f8f8f8"
      dark = "#252627"

  [params.search]
    enable = true
    type = "fuse"

  [params.header]
    [params.header.title]
      logo = "/logo.png"
      name = "bingo's log"
    [params.header.subtitle]
      name = "记录生活，分享知识"
      typeit = true

  [params.footer]
    enable = true
    copyright = true
    author = true
    since = "2021"
    wordCount = true
    icp = '<a rel="license external nofollow noopener noreferrer" href="https://beian.miit.gov.cn/" target="_blank">闽ICP备2021018106号-3</a>'
    [params.footer.siteTime]
      enable = true
      animate = true
      value = "2021-11-04T09:09:36+08:00"
    [params.footer.order]
      powered = 0
      copyright = 2
      statistics = 1

  [params.section]
    [params.section.recentlyUpdated]
      enable = true
      rss = true

  [params.tagcloud]
    enable = true

  [params.home]
    [params.home.profile]
      enable = true
      gravatarEmail = "bingo084@outlook.com"
      avatarMenu = "/categories/"
      title = "Hi, I'm bingo."
      subTitle = "Keep learning, keep thinking."

  [params.social]
    GitHub = "bingo084"
    Telegram = "bingo084"
    Steam = "bingo084"
    Bilibili = "37556054"
    QQ = "954701435"
    Email = "bingo084@outlook.com"
    RSS = true

  [params.page]
    lightgallery = "force"
    linkToSource = false
    linkToReport = false
    pageStyle = "narrow"
    collectionList = true
    collectionNavigation = true

    [params.page.expirationReminder]
      enable = true
    [params.page.heading]
      [params.page.heading.number]
        enable = true
    [params.page.code]
      maxShownLines = 20
    [params.page.cacheRemoteImages]
      enable = true
      replace = true
    [params.page.related]
      enable = true
    [params.page.share]
      enable = false
    [params.page.comment]
      enable = true
      [params.page.comment.giscus]
        enable = true
        repo = "bingo084/bingo084.github.io"
        repoId = "R_kgDOK5hh3w"
        category = "Announcements"
        categoryId = "DIC_kwDOK5hh384Cb1-h"
        mapping = "title"
        strict = "1"
        darkTheme = "noborder_gray"

  [params.ibruce]
    enable = true
    enablePost = true

  [params.analytics]
    enable = true
    [params.analytics.google]
      id = "G-GHBP2G0JY9"

  [params.cookieconsent]
    enable = false

  [params.gravatar]
    enable = true

  [params.readingProgress]
    enable = true
    light = "orange"
    dark = "orange"
  
  [params.pace]
    enable = true
    color = "orange"

  [params.customFilePath]
    profile = "custom/profile.html"
    footer = "custom/footer.html"

# -------------------------------------------------------------------------------------
# Markup related configuration in Hugo
# See: https://gohugo.io/getting-started/configuration-markup/
# -------------------------------------------------------------------------------------

[markup]
  [markup.highlight]
    lineNos = true
    noClasses = false
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = true
        eastAsianLineBreaksStyle = 'simple'
        enable = true
        escapedSpace = false
    [markup.goldmark.renderer]
      unsafe = true

# -------------------------------------------------------------------------------------
# Privacy Configuration
# See: https://gohugo.io/about/hugo-and-gdpr/
# -------------------------------------------------------------------------------------

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# -------------------------------------------------------------------------------------
# Customizing Output Formats
# See: https://gohugo.io/templates/output-formats/#customizing-output-formats
# -------------------------------------------------------------------------------------

[outputs]
  home = ["HTML", "RSS", "JSON", "baidu_urls", "archives", "offline", "readme"]

[related]
  includeNewer = true
  threshold = 80
[[related.indices]]
    name = 'keywords'
    weight = 100
