name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN_DEPLOY }}
          fetch-depth: 0

      - name: Checkout private
        uses: actions/checkout@v4
        with:
          repository: bingo084/blog-private
          token: ${{ secrets.PERSONAL_TOKEN_DEPLOY }}
          path: private
          fetch-depth: 0

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true

      - name: Hugo build
        run: hugo --cleanDestinationDir --minify

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          repo: bingo084/bingo084.github.io
          target_branch: main
          build_dir: public
          keep_history: true
          commit_message: ${{ github.event.head_commit.message }}
        env:
          GH_PAT: ${{ secrets.PERSONAL_TOKEN_DEPLOY }}
